apiVersion: v1
kind: Service
metadata:
  name: tiller-deploy
  namespace: kube-system
  labels:
    app: helm
    name: tiller
spec:
  selector:
    app: helm
    name: tiller
  ports:
    - name: tiller
      port: 44134
      targetPort: 44134
      nodePort: 32767
  type: NodePort
